# Generated by Django 3.2.23 on 2023-12-19 00:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Advert')),
                ('title', models.CharField(max_length=150)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UpdatePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='Media')),
                ('catgories', models.CharField(choices=[('News', 'News'), ('Education', 'Education'), ('Politics', 'Politics'), ('Sport', 'Sport'), ('Entertainmnt', 'Entertaiment')], default='News', max_length=100)),
                ('discriptions', ckeditor.fields.RichTextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
        ),
    ]
