# Generated by Django 5.0.1 on 2024-10-08 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_profile_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatepost',
            name='catgories',
            field=models.CharField(choices=[('News', 'News'), ('Education', 'Education'), ('Politics', 'Politics'), ('Sport', 'Sport'), ('Entertainment', 'Entertainment')], default='News', max_length=100),
        ),
        migrations.AlterField(
            model_name='updatepost',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='updatepost',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
