# Generated by Django 5.0.1 on 2024-10-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_updatepost_catgories_alter_updatepost_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatepost',
            name='catgories',
            field=models.CharField(choices=[('News', 'News'), ('Education', 'Education'), ('Politics', 'Politics'), ('Sport', 'Sport'), ('Entertaiment', 'Entertaiment')], default='News', max_length=100),
        ),
    ]
